### ISSUE TITLE
Class Diagram

### ISSUE THREAD

**Issue by SaitTalhaNisanci** [bounswe/bounswe2016group8#23]
How can I see our class diagram big enough to read other than opening the link directly ? it looks pretty small right now.

**Comment by SaitTalhaNisanci** [comment]
I should have asked this question in general actually not just for the class diagram

**Comment by ahmetenes** [comment]
You can use the zoom function of your browser. It can be used via ctrl+ whell up

**Comment by SaitTalhaNisanci** [comment]
I know that but it is a little bit tricky :) I was trying to find something more professional

**Comment by ozankep** [comment]
if you open in a new tab at Chrome, it can be bigger 
here is the link
https://camo.githubusercontent.com/ca9c395abe4c2d22874db016a9e9eb93beed6c61/687474703a2f2f692e696d6775722e636f6d2f6f55734a4d44582e706e67
