### ISSUE TITLE
Theme/feature

### ISSUE THREAD

**Issue by ozankep** [bounswe/bounswe2016group8#9]
1. \- Sign  up / Sign In feature:
2. \- User profile page: follower following feature, student tracking system, topic’i rateleme feature‘ı
3. \- Notification
4. \- her topic için anasayfa olmalı,sayfada description. Alakalı sorular, glossary, alakalı test de bu sayfadan linki olmalı
5. \- Browse Topics sayfasında tüm topicler explore edilebilir, search de olcak, sort olcak, filter, hot topics
6. \- Browse Questions sayfası olcak, topiclere bağlı
7. \- Reccomendation engine based on search
8. \- Kullanıcı yetkilendirme authorization (iki farklı kullanıcı student, teacher) share için enroll?
9. \- Multiple language support
10. \- Topic ve Question rate
11. \- Tüm topicler herkese açık ama bazı topicler için testler mandatory
12. \- Tag sistemi

**Comment by ozankep** [comment]
i will write 
signup / signin 
profil page

**Comment by ozankep** [comment]
I opened wiki page for themes & features

**Comment by seymaertem** [comment]
I will write
Notification
Rating system 
Tag system

**Comment by SaitTalhaNisanci** [comment]
I will write
Recommendation
History System

**Comment by ozankep** [comment]
@seymaertem user stories'i wiki anasayfasında themes'in altına mı koysak? :)

**Comment by seymaertem** [comment]
@ozankep haklısın yanlış yapmışım :). düzelttim

**Comment by ahmetenes** [comment]
I added some user stories to Topics Page, Question Page, Language Support
